Query: 1
/* IBM_DMCTOP */
WITH AGENT_TAB AS (
	SELECT
		EVENT_STATE,
		EVENT_TYPE,
		CAST(
			(
				(
					CAST(JULIAN_DAY(CURRENT TIMESTAMP) AS DECFLOAT(34)) * 86400 + EXTRACT(
						HOUR
						FROM
							CURRENT TIMESTAMP
					) * 60 * 60 + EXTRACT(
						MINUTE
						FROM
							CURRENT TIMESTAMP
					) * 60 + EXTRACT(
						SECOND
						FROM
							CURRENT TIMESTAMP
					) - (
						CAST(
							JULIAN_DAY(AGENT_STATE_LAST_UPDATE_TIME) AS DECFLOAT(34)
						) * 86400 + EXTRACT(
							HOUR
							FROM
								AGENT_STATE_LAST_UPDATE_TIME
						) * 60 * 60 + EXTRACT(
							MINUTE
							FROM
								AGENT_STATE_LAST_UPDATE_TIME
						) * 60 + EXTRACT(
							SECOND
							FROM
								AGENT_STATE_LAST_UPDATE_TIME
						)
					)
				)
			) AS DOUBLE
		) AS IDLE_DURATION
	FROM
		TABLE(MON_GET_AGENT(NULL, NULL, NULL, 0))
	WHERE
		APPLICATION_HANDLE <> 0
		AND AGENT_STATE = 'ACTIVE'
),
TOTAL_TAB AS (
	SELECT
		COUNT(*) AS TOTAL_CONN
	FROM
		AGENT_TAB
),
ACT_TAB AS (
	SELECT
		COUNT(*) AS ACTIVE_CONN
	FROM
		AGENT_TAB
	WHERE
		EVENT_STATE = 'EXECUTING'
		AND EVENT_TYPE = 'PROCESS'
		AND IDLE_DURATION < 15
)
SELECT
	TOTAL_CONN,
	ACTIVE_CONN
FROM
	TOTAL_TAB,
	ACT_TAB