Query: 1
/* IBM_DMCTOP */
WITH COORD_AGENT AS (
	SELECT
		MEMBER,
		MIN(AGENT_TID) AS AGENT_TID
	FROM
		TABLE (MON_GET_AGENT(NULL, NULL, NULL, 0))
	WHERE
		AGENT_TYPE = 'COORDINATOR'
		AND APPLICATION_HANDLE = 37890
	GROUP BY
		MEMBER
),
MEM_POOL AS (
	SELECT
		MEMBER,
		SUM(MEMORY_POOL_USED) * 1024 AS MEMORY_POOL_USED_BYTES
	FROM
		TABLE(MON_GET_MEMORY_POOL(NULL, CURRENT_SERVER, 0))
	WHERE
		APPLICATION_HANDLE = 37890
	GROUP BY
		MEMBER
)
SELECT
	C.APPLICATION_HANDLE,
	MIN(C.APPLICATION_NAME) AS APPLICATION_NAME,
	MIN(C.CONNECTION_START_TIME) AS CONNECTION_START_TIME,
	MIN(C.UOW_START_TIME) AS UOW_START_TIME,
	MIN(C.SYSTEM_AUTH_ID) AS SYSTEM_AUTH_ID,
	MIN(C.EXECUTION_ID) AS EXECUTION_ID,
	MIN(C.COORD_MEMBER) AS COORD_MEMBER,
	MIN(AGENT_TID) AS AGENT_TID,
	MIN(C.CLIENT_PID) AS CLIENT_PID,
	SUM(C.TOTAL_HASH_JOINS) AS TOTAL_HASH_JOINS,
	SUM(C.TOTAL_HASH_LOOPS) AS TOTAL_HASH_LOOPS,
	SUM(
		C.HASH_JOIN_OVERFLOWS + HASH_JOIN_SMALL_OVERFLOWS
	) AS HASH_JOIN_OVF,
	SUM(
		C.SELECT_SQL_STMTS + C.DDL_SQL_STMTS + C.UID_SQL_STMTS
	) AS SQL_STMTS,
	SUM(C.TOTAL_SORTS) AS TOTAL_SORTS,
	SUM(C.TOTAL_SECTION_SORT_TIME) AS TOTAL_SECTION_SORT_TIME_MS,
	SUM(C.SORT_OVERFLOWS) AS SORT_OVERFLOWS,
	SUM(C.ROWS_READ) AS ROWS_READ,
	SUM(C.ROWS_RETURNED) AS ROWS_RETURNED,
	CASE
		WHEN SUM(C.ROWS_RETURNED) = 0 THEN NULL
		ELSE CAST(
			SUM(ROWS_READ) * 1.0 / SUM(C.ROWS_RETURNED) AS DOUBLE
		)
	END AS AVERAGE_READS_PER_ROW,
	SUM(C.ROWS_MODIFIED) AS ROWS_MODIFIED,
	SUM(C.ROWS_INSERTED) AS ROWS_INSERTED,
	SUM(C.ROWS_UPDATED) AS ROWS_UPDATED,
	SUM(C.ROWS_DELETED) AS ROWS_DELETED,
	SUM(C.NUM_LOCKS_HELD) AS NUM_LOCKS_HELD,
	SUM(C.TOTAL_APP_COMMITS + C.TOTAL_APP_ROLLBACKS) AS TOTAL_TRANS,
	SUM(MEM_POOL.MEMORY_POOL_USED_BYTES) AS MEMORY_POOL_USED_BYTES,
	SUM(C.DYNAMIC_SQL_STMTS) AS DYNAMIC_SQL_STMTS,
	SUM(C.STATIC_SQL_STMTS) AS STATIC_SQL_STMTS,
	CAST(SUM(TOTAL_CPU_TIME) / 1000.0 AS DOUBLE) AS TOTAL_CPU_TIME_MS,
	CASE
		WHEN SUM(C.DYNAMIC_SQL_STMTS + C.STATIC_SQL_STMTS) = 0 THEN NULL
		ELSE CAST(
			SUM(TOTAL_CPU_TIME) / 1000.0 / SUM(C.DYNAMIC_SQL_STMTS + C.STATIC_SQL_STMTS) AS DOUBLE
		)
	END AS AVG_CPU_TIME_MS_PER_STMT
FROM
	TABLE(MON_GET_CONNECTION(NULL, -1, 1)) C
	LEFT OUTER JOIN COORD_AGENT ON C.MEMBER = COORD_AGENT.MEMBER
	LEFT OUTER JOIN MEM_POOL ON C.MEMBER = MEM_POOL.MEMBER
WHERE
	C.APPLICATION_HANDLE = 37890
GROUP BY
	C.APPLICATION_HANDLE