CREATE OR REPLACE PROCEDURE sp_GetIndexForTable(in tabschema varchar(20), in tabname varchar(20))
	RESULT SETS 1
	LANGUAGE SQL
BEGIN
	SELECT VARCHAR(S.INDSCHEMA, 10) AS INDSCHEMA, VARCHAR(S.INDNAME, 10) AS INDNAME, T.DATA_PARTITION_ID, T.MEMBER, T.INDEX_SCANS, T.INDEX_ONLY_SCANS FROM TABLE(SYSPROC.MON_GET_INDEX(tabschema,tabname, -2)) as T, SYSCAT.INDEXES AS S
	WHERE T.TABSCHEMA = S.TABSCHEMA AND T.TABNAME = S.TABNAME AND T.IID = S.IID ORDER BY INDEX_SCANS DESC;
END
